// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4aRa4JITZV9zShJTa5A2T6GEiGOX3W8',
    appId: '1:133412579657:web:8aee1328b441c207cf1298',
    messagingSenderId: '133412579657',
    projectId: 'legallens-ai-d46f1',
    authDomain: 'legallens-ai-d46f1.firebaseapp.com',
    storageBucket: 'legallens-ai-d46f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDddHUKKnguN_6uHeXL9hMFLAztB9cf-dw',
    appId: '1:133412579657:android:2aeeccd0eba451f6cf1298',
    messagingSenderId: '133412579657',
    projectId: 'legallens-ai-d46f1',
    storageBucket: 'legallens-ai-d46f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCg6jvAHV-pKGRKhpEPnK3bkJfkMo-_Vc',
    appId: '1:133412579657:ios:5dac6f1bfa207b0dcf1298',
    messagingSenderId: '133412579657',
    projectId: 'legallens-ai-d46f1',
    storageBucket: 'legallens-ai-d46f1.firebasestorage.app',
    iosBundleId: 'com.jaydeo.legallens.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCg6jvAHV-pKGRKhpEPnK3bkJfkMo-_Vc',
    appId: '1:133412579657:ios:5dac6f1bfa207b0dcf1298',
    messagingSenderId: '133412579657',
    projectId: 'legallens-ai-d46f1',
    storageBucket: 'legallens-ai-d46f1.firebasestorage.app',
    iosBundleId: 'com.jaydeo.legallens.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX4aRa4JITZV9zShJTa5A2T6GEiGOX3W8',
    appId: '1:133412579657:web:2d4b402e9a419b58cf1298',
    messagingSenderId: '133412579657',
    projectId: 'legallens-ai-d46f1',
    authDomain: 'legallens-ai-d46f1.firebaseapp.com',
    storageBucket: 'legallens-ai-d46f1.firebasestorage.app',
  );
}
